[legends]
KC_EXLM = !
KC_QUES = ? !
KC_GT = >
KC_LT = <
KC_HASH = #
KC_PERC = %
KC_AT = @
KC_DLR = $
KC_CIRC = ^
KC_LCBR = {
KC_LPRN = (
KC_LBRC = [
KC_RCBR = }
KC_RPRN = )
KC_RBRC = ]
KC_PIPE = |
KC_GRAVE = ` ~
KC_TILD = ~
KC_PLUS = +
KC_AMPR = &
KC_UNDS = _
KC_MINUS = - _
KC_EQL = = +
KC_SLASH = / ?
KC_COMM = , <
KC_DOT = . >
KC_ASTR = *
KC_BSLS = \ |
KC_BSLASH = \ |
KC_QUOTE = ' "
KC_DQUO = "
KC_SCLN = : ;
KC_ENTER = âŽ
LSFT(KC_ENTER) = SFT âŽ
KC_PSCR = PrintSc
KC_NLCK = NumLock
KC_SLCK = ScrLock
KC_INS = Ins
_ =
__ =

LT(SPANISH,KC_ESC) = SPA/ESC
MO(LAYERS) = LAYERS
KC_AUDIO_VOL_DOWN = VOL -
KC_AUDIO_VOL_UP   = VOL +
KC_MEDIA_NEXT_TRACK = â­ï¸
KC_MEDIA_PREV_TRACK = â®ï¸
KC_MEDIA_PLAY_PAUSE = â¯ï¸
LT(NAV,KC_SPACE) = NAV/SPC
SYM_ENTER = SYM/âŽ

SPA_G = SPA/G
SPA_H = SPA/H
SPC_G = SPA/G
SPC_M = SPA/M

HOME_A= LâŽˆ/A
HOME_S= LâŽ‡/S
HOME_D= Lâ‡§/D
HOME_F= Lâ—†/F

HOME_J= LâŽˆ/J
HOME_K= LâŽ‡/K
HOME_L= Lâ‡§/L
HOME_SCLN= Lâ—†/;

CM_A = LâŽˆ/A
CM_R = LâŽ‡/R
CM_S = Lâ‡§/S
CM_T = Lâ—†/T
CM_N = LâŽˆ/N
CM_E = LâŽ‡/E
CM_I = Lâ‡§/I
CM_O = Lâ—†/O


KC_UP = â†‘
KC_LEFT = â†
KC_DOWN = â†“
KC_RIGHT = â†’

CODE_BCK = CBCK
CODE_FWD = CFWD
KC_BSPACE = BSPC

KC_PREV_TAB = TAB â†
KC_NEXT_TAB = TAB â†’

LGUI(LCTL(LSFT(KC_4))) = ðŸ“·
KC_DELETE = DEL
MV_LSPC = SPC â†
MV_RSPC = SPC â†’
SW_LANG = LANG

SC_UNDO = UNDO
SC_CUT = CUT
SC_COPY = COPY
SC_PASTE = PASTE
SC_REDO = REDO

KC_MS_U = MOUSE â†‘
KC_MS_D = MOUSE â†“
KC_MS_L = MOUSE â†
KC_MS_R = MOUSE â†’
KC_WH_U = WHEEL â†‘
KC_WH_D = WHEEL â†“

KC_LGUI = Lâ—†
KC_RGUI = Râ—†
KC_LALT = LâŽ‡
KC_LSFT = Lâ‡§
KC_RSFT = Râ‡§
KC_LCTL = LâŽˆ
KC_RCTL = RâŽˆ

UMLAU_U = Ãœ
ACUTE_A = Ã
ACUTE_E = Ã‰
ACUTE_I = Ã
ACUTE_O = Ã“
ACUTE_U = Ãš
TILDE_N = Ã‘
TD_DOT = . >

NK_ON = NKROon
NK_OFF = NKROoff

STN_N1 = #1
STN_N2 = #2
STN_N3 = #3
STN_N4 = #4
STN_N5 = #5
STN_N6 = #6
STN_N7 = #7
STN_N8 = #8
STN_N9 = #9
STN_NA = NA
STN_S1 = S1
STN_TL = T-
STN_PL = P-
STN_HL = H-
STN_ST1 = *1
STN_ST3 = *3
STN_FR = -F
STN_PR = -P
STN_LR = -L
STN_TR = -T
STN_DR = -D
STN_S2 = S2
STN_KL = K-
STN_WL = W-
STN_RL = R- 
STN_ST2 = *2
STN_ST4 = *4
STN_RR = -R
STN_BR = -B
STN_GR = -G
STN_SR = -S
STN_ZR = -Z
STN_A = A-
STN_O = O-
STN_E = -E
STN_U = -U

SH_OS = SWAPHNDS
